coverage:
  status:
    project:
      default:
        target: 92%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
