#!/usr/bin/env python3
"""Generate or verify KiCad adapter matrix JSON and Markdown artifacts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "integrations" / "common" / "kicad-adapter-matrix.json"
DOC_PATH = ROOT / "docs" / "compatibility" / "kicad-adapter-matrix.generated.md"


def _payload() -> dict[str, Any]:
    from kicad_mcp.adapter_matrix import build_adapter_matrix_payload

    return build_adapter_matrix_payload()


def _json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# KiCad Adapter Matrix",
        "",
        "> Generated by `scripts/build_adapter_matrix.py`; do not edit by hand.",
        "",
        "The matrix keeps KiCad 10.0.x as the stable baseline and treats KiCad 11 as a preview",
        "until separate read, write, and export canaries pass. Runtime selection is",
        "fail-closed: a tool declaring an IPC or CLI requirement is not silently",
        "redirected to a file parser.",
        "",
        "| Category | Tools | KiCad 11 | Preferred adapters | Canary surfaces | Mutation guard |",
        "| --- | ---: | --- | --- | --- | --- |",
    ]
    categories = payload["categories"]
    scenarios = payload["scenarios"]
    k11_categories = scenarios["kicad11Headless"]["categories"]
    for category in sorted(categories):
        policy = categories[category]
        runtime = k11_categories[category]
        lines.append(
            "| `{category}` | {count} | `{status}` | {backends} | {surfaces} | {guard} |".format(
                category=category,
                count=runtime["toolCount"],
                status=policy["kicad11Support"],
                backends=" → ".join(f"`{item}`" for item in policy["preferredBackends"]),
                surfaces=", ".join(f"`{item}`" for item in policy["canarySurfaces"]),
                guard=(f"`{policy['mutationGuard']}`" if policy["mutationGuard"] else "—"),
            )
        )
    lines.extend(
        [
            "",
            "## Reference scenarios",
            "",
            "| Scenario | Available tools | Blocked tools | Selected backends |",
            "| --- | ---: | ---: | --- |",
        ]
    )
    for scenario_name in ("kicad10Gui", "kicad11Headless", "degradedNoKiCad"):
        category_rows = scenarios[scenario_name]["categories"].values()
        available = sum(int(row["availableCount"]) for row in category_rows)
        category_rows = scenarios[scenario_name]["categories"].values()
        blocked = sum(int(row["blockedCount"]) for row in category_rows)
        counts: dict[str, int] = {}
        for row in scenarios[scenario_name]["categories"].values():
            for backend, count in row["selectedBackends"].items():
                counts[backend] = counts.get(backend, 0) + int(count)
        rendered = ", ".join(f"`{name}`: {count}" for name, count in sorted(counts.items()))
        lines.append(f"| `{scenario_name}` | {available} | {blocked} | {rendered} |")
    lines.extend(
        [
            "",
            "## Mutation safety",
            "",
            "- Schematic file writes use atomic replacement plus structural fingerprint",
            "  loss detection.",
            "- PCB file writes use transactional temporary-file replacement and post-write",
            "  parsing.",
            "- IPC writes require a live KiCad GUI document or an explicitly asserted",
            "  KiCad 11 headless API server.",
            "- Native exports require `kicad-cli` and validate isolated output artifacts.",
            "- The SWIG `pcbnew` module remains forbidden in production code.",
            "",
        ]
    )
    return "\n".join(lines)


def _check(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    payload = _payload()
    outputs = {JSON_PATH: _json_text(payload), DOC_PATH: _markdown(payload)}
    if args.check:
        stale = [
            str(path.relative_to(ROOT)) for path, text in outputs.items() if not _check(path, text)
        ]
        if stale:
            print("KiCad adapter matrix artifacts are stale:", file=sys.stderr)
            for path in stale:
                print(f"- {path}", file=sys.stderr)
            return 1
        print("KiCad adapter matrix artifacts OK")
        return 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print("Generated KiCad adapter matrix artifacts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
